name: Docker Image CI
on:
  push:
    branches: 
      - master
      - demo-*
    tags: 
      - 'v*'

jobs:
  build_and_publish:
    if: github.repository == 'genome-nexus/genome-nexus-annotation-pipeline'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Install root POM (master)
        run: mvn install -N -DskipTests
      - name: Build Maven Project
        run: mvn clean install -DskipTests
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            genomenexus/gn-annotation-pipeline
          # The latest tag will also be generated on tag event with a valid semver tag
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      # The following two actions are required to build multi-platform images
      # buildx is an extension of docker build, QUEM is used to convert the binary to varies architecture
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Docker Image on Tag
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha
